theme:minima
title: Mahdi's site
author: Mahdi
email: mboua1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is the coolest website on the planet.

# social links
twitter_username: Mahdi's.cool
github_username:  Mahdi's.cool


show_excerpts: true # set to false to remove excerpts on the homepage
